TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += wbvalve.db
DATA += wbvalve.proto

#=======================================
include $(TOP)/configure/RULES
